### ISSUE TITLE
Encoder

### ISSUE THREAD

**Issue by Pownator** [AversivePlusPlus/hal-stm32cubef4#1]
The encoder value works from 0 to 65535 but is never negative. Is this normal ?

**Comment by astralien3000** [comment]
It is normal ^^, the counter registers are of type "u16", unsigned 16 bits integers.
If you want to avoid the overflow (or underflow, in this case) problem for tests, you can set the initial value of the counter to 65536/2.
But you will have to deal with the overflow anyway.

**Comment by Pownator** [comment]
Ok thank you !
